In [5]:
# Storing variables
firstname = input("what is your name ?")
secondname = input("Waht is your surname ?")
print("hello  " + firstname + " " + secondname)

hellofaouez zaghouani


In [11]:
# Storing numbers
first = input("what is your first number ?")
second = input("Waht is your econd number ?")
print(float(first) + float(second))

10.399999999999999


In [13]:
#Making Decision with code
deposit = input("how much would you like to deposit ?")
if (float(deposit) > 100) and (float(deposit) < 200):
    print("you get a free toast")
else:
    print("enjoy your mug")
print("Have a nice day")


enjoy your mug
Have a nice day


In [1]:
#repeating events boucle for
for i in range(4):
    print("i a pour valeur", i)

i a pour valeur 0
i a pour valeur 1
i a pour valeur 2
i a pour valeur 3


In [9]:
#repeating events boucle while
x = 1
while x <= 10:
    print("x a pour valeur", x)
    x = x * 2

x a pour valeur 1
x a pour valeur 2
x a pour valeur 4
x a pour valeur 8


In [8]:
#Create a file in python
myFile = open("intro_text.txt", "w")
myFile.write("Hi there is my first line")
myFile.close()

In [57]:
def printmessage(m, n):
    message = m + '  '+n
    print(message)
    return
m='bonjour'
n='faouez'
printmessage(m, n)

bonjour  faouez


In [ ]:
travail a faire 
Ecrire une fonction permettant de faire la somme de deux entiers m et n,

In [58]:
def somme(a,b):
    s=a+b
    print(s)
    return
a=2
b=4
somme(a,b)

6


I. Undrestanding Data Types in python 

1. Fixed-Type Arrays in Python

Python offers several different options for storing data in efficient, fixed-type data buffers. The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [62]:
import array
L = list(range(20))
A = array.array('i', L)
A

array('B', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Here 'i' is a type code indicating the contents are integers.

Much more useful, however, is the ndarray object of the NumPy package. While Python's array object provides efficient storage of array-based data, NumPy adds to this efficient operations on that data. We will explore these operations in later sections; here we'll demonstrate several ways of creating a NumPy array.

We'll start with the standard NumPy import, under the alias np:
#to install numpy
pip install numpy
on utilise as pour creer une abreviation de la bibliotheque

In [2]:
import numpy as np

In [26]:
np.__version__

'1.18.1'

In [63]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the buil

2. Creating Arrays from Python Lists
First, we can use np.array to create arrays from Python lists:

In [67]:
# integer array:
#L = [1, 4, 2, 5, 3]
L=list(range(20))
np.array(L)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [28]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [68]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.])

Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:
The inner lists are treated as rows of the resulting two-dimensional array.

In [80]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 10) for i in [0, 20, 40, 50]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

3. Creating Arrays from Scratch
Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [82]:
# Create a length-10 integer array filled with zeros
np.zeros((5, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [5]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 4)

array([ 0,  4,  8, 12, 16])

In [8]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [9]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((5, 5))

array([[0.2800047 , 0.51079701, 0.73715534, 0.71352603, 0.59441462],
       [0.12573706, 0.84244873, 0.77741228, 0.07561872, 0.09540456],
       [0.69580116, 0.96610794, 0.3813047 , 0.44479023, 0.04760917],
       [0.00947537, 0.39641062, 0.48804709, 0.90399039, 0.86629547],
       [0.98681952, 0.60729134, 0.72182987, 0.24625901, 0.74560827]])

In [37]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.37970633, -0.3278064 , -1.7645601 ],
       [-0.0526408 ,  2.5222992 ,  0.66756127],
       [-1.5948453 , -1.49805537,  1.4906114 ]])

In [10]:
# Create a 3x3 array of random integers in the interval [0, 10])
np.random.randint(0, 10, (5, 3))

array([[0, 2, 2],
       [1, 9, 8],
       [3, 8, 8],
       [9, 5, 4],
       [4, 5, 0]])

In [12]:
# Create a 3x3 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
#The empty() function is used to create a new array of given shape and type, without initializing entries
np.empty(8)

array([0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 7.67e-321,
       0.00e+000, 0.00e+000])

4. NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table. Note that when constructing an array, they can be specified using a string:

In [41]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [18]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Data type	Description
bool_	Boolean (True or False) stored as a byte
int_	Default integer type (same as C long; normally either int64 or int32)
intc	Identical to C int (normally int32 or int64)
intp	Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8	Byte (-128 to 127)
int16	Integer (-32768 to 32767)
int32	Integer (-2147483648 to 2147483647)
int64	Integer (-9223372036854775808 to 9223372036854775807)
uint8	Unsigned integer (0 to 255)
uint16	Unsigned integer (0 to 65535)
uint32	Unsigned integer (0 to 4294967295)
uint64	Unsigned integer (0 to 18446744073709551615)
float_	Shorthand for float64.
float16	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64	Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_	Shorthand for complex128.
complex64	Complex number, represented by two 32-bit floats
complex128	Complex number, represented by two 64-bit floats

5. Créer les tableaux directement

Il est souvent plus efficace, surtout pour les tableaux larges, de les créer directement. Numpy contient plusieurs fonctions pour cette tâche.

6. Les propriétés des tableaux

Chaque tableau Numpy a des propriétés qui se révèlent souvent utiles.

In [20]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int32


7. Accéder à un seul élément

In [33]:
print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,2])
print(x2)

# On peut aussi modifier les valeurs
x1[1] = "20"
print(x1)

# Attention au type
x1[1] = 3.14
print(x1)

[5 3 3 3 7 9]
5
9
0
[[3 0 0 6]
 [0 6 3 3]
 [8 8 8 2]]
[ 5 20  3  3  7  9]
[5 3 3 3 7 9]


8. Accéder à plusieurs éléments

De la même façon que nous pouvons indexer des éléments grâce à  [], nous pouvons accéder à un ensemble d'éléments en combinant  []  et  :. La syntaxe suit une règle simple :  x[début:fin:pas].

In [47]:
print(x1[:5])  # Les cinq premiers éléments

print(x1[5:])  # Les éléments à partir de l'index 5

print(x1[::2])  # Un élément sur deux

[5 0 3 3 7]
[9]
[5 3 7]


Si le pas est négatif, le début et la fin du slice sont inversés. On peut utiliser cette propriété pour inverser un tableau.

In [35]:
x1[::-1]

array([9, 7, 3, 3, 3, 5])

On peut accéder de la même façon aux éléments d'un tableau multi-dimensionnel. Par exemple, on a souvent besoin d'accéder à une ligne ou une colonne d'une matrice.

In [51]:
print(x2)

x2[0,:] # La première ligne

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([3, 5, 2, 4])

9. Concaténation
On peut concaténer deux ou plusieurs tableaux.

In [52]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Exercice :
(1) Écrire un programme pour renverser un tableau.  Tableau : [12 13 14 15 16 17 18 19 20 ]
Tableau renversé : [ 20 19 18 17 16 15 14 13 12]
(2) Écrire un programme pour transformer un tableau de type int en un tableau de type
float.
(3) Écrire un programme qui des 0 tout autour d’un tableau.
(4) Écrire un programme qui renvoie un tableau dont les lignes sont renversées
(5) Écrire un programme qui les valeurs puis les indices des éléments supérieurs à 10


In [37]:
x = np.arange (12, 21)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20]
Reverse array:
[20 19 18 17 16 15 14 13 12]


In [38]:
a = [1, 2, 3, 4]
x = np.array(a,dtype=float)
print(x)
x = np.asarray(a,dtype=float)

[1. 2. 3. 4.]


In [6]:
x = np.ones ((7 ,7))
print("Original array:")
print(x)
y = np.zeros ((x.shape [0]+2 ,x.shape [1]+2))
y[1:-1,1:-1] = x
print(y)


Original array:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
a=np.ones((7,7))
print(a.shape)

(7, 7)


In [17]:
A = np.array([[1 , 2, 3], [4 , 5, 6]])
print(A)
print(A.ndim)
print(A.mdim)
print(A.shape)
print(A.dtype)


[[1 2 3]
 [4 5 6]]
2


AttributeError: 'numpy.ndarray' object has no attribute 'mdim'

In [8]:
a=np.ones((7,7))
print(a)
c=np.zeros((9,9))
c[1:-1,1:-1]=a[:,:]
print(c)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [37]:
x = np.arange(12).reshape(3 ,4)
print(" Original array:")
print(x)
y = x[:,range(np.shape[1],-1,-1):]
print(y)

 Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


TypeError: 'function' object is not subscriptable

In [3]:
x = np.array ([[0 , 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x >10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Data Manipulation with Pandas

In [44]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['note1', 'note2', 'note3', 'note4'])
print(data)
print(data['note4'])

note1    0.25
note2    0.50
note3    0.75
note4    1.00
dtype: float64
1.0


As we see in the output, the Series wraps both a sequence of values and a sequence of indices, which we can access with the values and index attributes. The values are simply a familiar NumPy array:

In [39]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [40]:
data.index

RangeIndex(start=0, stop=4, step=1)